### ISSUE TITLE
Do Players really need to be managed by unique_ptr

### ISSUE THREAD

**Issue by Elried** [8INF840-uqac/Devoir1#5]
The Game class manages the 2 players as `std::unique_ptr`. However, the semantic seems wrong (the presence of both players is mandatory) and I do not see any reason to use pointers here.

**Comment by AmarOk1412** [comment]
Indeed.

Fixed. Thx.

**Comment by Elried** [comment]
In `Card.h(pp :p)` you still have the `memory` include which is now useless.
